const { getGoalFromInitTopic } = require("./AIGenerate")
const express = require("express");
const router = express.Router();

const starterTopics = [
  "Exploitation",
  "Colonialism",
  "Surveillance",
  "Manipulation",
  "Misinformation",
  "Propaganda",
  "Corruption",
  "Inequality",
  "Monopolization",
  "Radicalization",
  "Militarization",
  "Censorship",
  "Displacement",
  "Redlining",
  "Profiling",
  "Precarity",
  "Financialization",
  "Dehumanization",
  "Marginalization",
  "Polarization",
  "Consolidation",
  "Dispossession",
  "Overconsumption",
  "Obsolescence",
  "Suppression",
  "Oppression",
  "Segregation",
  "Exclusion",
  "Discrimination",
  "Erasure",
  "Appropriation",
  "Extinction",
  "Pollution",
  "Deforestation",
  "Degradation",
  "Contamination",
  "Scarcity",
  "Incarceration",
  "Fraud",
  "Gouging",
  "Hoarding",
  "Bias",
  "Cronyism",
  "Nepotism",
  "Authoritarianism",
  "Totalitarianism",
  "Retaliation",
  "Intimidation",
  "Weaponization",
  "Colonization",
  "Exhaustion",
  "Addiction",
  "Dependency",
  "Fragmentation",
  "Complacency",
  "Complicity",
  "Corrosion",
  "Destabilization",
  "Vulnerability",
  "Insecurity",
  "Radicalism",
  "Centralization",
  "Digitalization",
  "Autocracy",
  "Predation",
  "Commoditization",
  "Subjugation",
  "Disempowerment",
  "Evasion",
  "Misconduct",
  "Malfeasance",
  "Abuse",
  "Entrapment",
  "Intensification",
  "Proliferation",
  "Alienation",

  "Data exploitation",
  "Data colonialism",
  "Algorithmic bias",
  "Surveillance capitalism",
  "Privacy erosion",
  "Consent manipulation",
  "Biometric misuse",
  "Predictive policing",
  "Facial misidentification",
  "Data monopolies",
  "Information asymmetry",
  "E-waste dumping",
  "Mining exploitation",
  "Biodiversity collapse",
  "Habitat destruction",
  "Species extinction",
  "Climate migration",
  "Food insecurity",
  "Water scarcity",
  "Energy inequity",
  "Nuclear waste",
  "Industrial runoff",
  "Forced labor",
  "Child labor",
  "Human trafficking",
  "Modern slavery",
  "Prison labor",
  "Mass incarceration",
  "Voter suppression",
  "Gerrymandering tactics",
  "Discriminatory zoning",
  "Housing segregation",
  "Redlining legacy",
  "Health disparities",
  "Medical bias",
  "Pharmaceutical greed",
  "Patent hoarding",
  "Price gouging",
  "Corporate lobbying",
  "Regulatory capture",
  "Tax evasion",
  "State surveillance",
  "Mass monitoring",
  "Censorship regimes",
  "Information control",
  "Propaganda machinery",
  "Political corruption",
  "Election interference",
  "Militarized AI",
  "Autonomous weapons",
  "Cyber warfare",
  "Biometric databases",
  "Genetic surveillance",
  "DNA exploitation",
  "Data breaches",
  "Identity theft",
  "Ransomware attacks",
  "Infrastructure hacking",
  "Insider trading",
  "Market manipulation",
  "Financial fraud",
  "Crypto scams",
  "Token manipulation",
  "Pump schemes",
  "AI hallucinations",
  "Model opacity",
  "Training exploitation",
  "Data scraping",
  "Unpaid labeling",
  "Intellectual theft",
  "Copyright abuse",
  "Cultural appropriation",
  "Indigenous erasure",
  "Language extinction",
  "Digital divide",
  "Access inequality",
  "Tech elitism",
  "Education inequity",
  "Student debt",
  "Predatory lending",
  "Emotional manipulation",
  "Fear monetization",
  "Trauma exploitation",
  "Crisis profiteering",
  "Disaster capitalism",
  "War profiteering",
  "Security theater",
  "Liability avoidance",
  "Accountability gaps",
  "Ethics washing",
];

router.get("/", async (_req, res) => {

  const rndTopic = starterTopics[Math.floor(Math.random() * starterTopics.length)]
  const goalFromTopic = await getGoalFromInitTopic(rndTopic);

  res.json({
    topic: rndTopic, 
    goal: goalFromTopic ?? "NONE"
  });

})

module.exports = router;