const { getGoalFromInitTopic } = require("./AIGenerate")
const express = require("express");
const router = express.Router();

const starterTopics = [
  "Exploitation",
  "Colonialism",
  "Surveillance",
  "Manipulation",
  "Misinformation",
  "Propaganda",
  "Corruption",
  "Inequality",
  "Monopolization",
  "Radicalization",
  "Militarization",
  "Censorship",
  "Displacement",
  "Redlining",
  "Profiling",
  "Precarity",
  "Financialization",
  "Dehumanization",
  "Marginalization",
  "Polarization",
  "Consolidation",
  "Dispossession",
  "Overconsumption",
  "Obsolescence",
  "Suppression",
  "Oppression",
  "Segregation",
  "Exclusion",
  "Discrimination",
  "Erasure",
  "Appropriation",
  "Extinction",
  "Pollution",
  "Deforestation",
  "Degradation",
  "Contamination",
  "Scarcity",
  "Incarceration",
  "Fraud",
  "Gouging",
  "Hoarding",
  "Bias",
  "Cronyism",
  "Nepotism",
  "Authoritarianism",
  "Totalitarianism",
  "Retaliation",
  "Intimidation",
  "Weaponization",
  "Colonization",
  "Exhaustion",
  "Addiction",
  "Dependency",
  "Fragmentation",
  "Complacency",
  "Complicity",
  "Corrosion",
  "Destabilization",
  "Vulnerability",
  "Insecurity",
  "Radicalism",
  "Centralization",
  "Digitalization",
  "Autocracy",
  "Predation",
  "Commoditization",
  "Subjugation",
  "Disempowerment",
  "Evasion",
  "Misconduct",
  "Malfeasance",
  "Abuse",
  "Entrapment",
  "Intensification",
  "Proliferation",
  "Alienation",

  "Data exploitation",
  "Data colonialism",
  "Algorithmic bias",
  "Surveillance capitalism",
  "Privacy erosion",
  "Consent manipulation",
  "Biometric misuse",
  "Predictive policing",
  "Facial misidentification",
  "Data monopolies",
  "Information asymmetry",
  "Digital redlining",
  "Shadow profiling",
  "Behavioral targeting",
  "Data laundering",
  "Metadata harvesting",
  "Emotional AI",
  "Deepfake abuse",
  "Synthetic propaganda",
  "Misinformation networks",
  "Disinformation campaigns",
  "Platform manipulation",
  "Echo chambers",
  "Content radicalization",
  "Troll farms",
  "Bot amplification",
  "Cyber harassment",
  "Online radicalization",
  "Attention extraction",
  "Addictive design",
  "Neurocapitalism",
  "Digital dependency",
  "Gig exploitation",
  "Worker surveillance",
  "Algorithmic management",
  "Automation displacement",
  "Wage suppression",
  "Labor precarity",
  "Union busting",
  "Greenwashing tactics",
  "Carbon colonialism",
  "Climate denial",
  "Toxic dumping",
  "Resource extraction",
  "Ocean acidification",
  "Air contamination",
  "Water privatization",
  "Environmental racism",
  "Land dispossession",
  "Deforestation incentives",
  "Overconsumption culture",
  "Fast fashion waste",
  "E-waste dumping",
  "Planned obsolescence",
  "Mining exploitation",
  "Biodiversity collapse",
  "Habitat destruction",
  "Species extinction",
  "Climate migration",
  "Food insecurity",
  "Water scarcity",
  "Energy inequity",
  "Nuclear waste",
  "Industrial runoff",
  "Supply chain opacity",
  "Conflict minerals",
  "Forced labor",
  "Child labor",
  "Human trafficking",
  "Modern slavery",
  "Prison labor",
  "Mass incarceration",
  "For-profit prisons",
  "Policing militarization",
  "Border militarization",
  "Refugee criminalization",
  "Voter suppression",
  "Gerrymandering tactics",
  "Discriminatory zoning",
  "Housing segregation",
  "Redlining legacy",
  "Health disparities",
  "Medical bias",
  "Pharmaceutical greed",
  "Patent hoarding",
  "Price gouging",
  "Corporate lobbying",
  "Regulatory capture",
  "Tax evasion",
  "Offshore shelters",
  "Wealth hoarding",
  "State surveillance",
  "Mass monitoring",
  "Censorship regimes",
  "Information control",
  "Journalist intimidation",
  "Propaganda machinery",
  "Political corruption",
  "Election interference",
  "Authoritarian drift",
  "Militarized AI",
  "Autonomous weapons",
  "Drone warfare",
  "Cyber warfare",
  "Biometric databases",
  "Genetic surveillance",
  "DNA exploitation",
  "Data breaches",
  "Identity theft",
  "Ransomware attacks",
  "Infrastructure hacking",
  "Critical vulnerabilities",
  "Encryption backdoors",
  "Corporate espionage",
  "Insider trading",
  "Market manipulation",
  "Speculative bubbles",
  "Financial fraud",
  "Ponzi schemes",
  "Crypto scams",
  "Token manipulation",
  "Pump schemes",
  "AI hallucinations",
  "Model opacity",
  "Training exploitation",
  "Data scraping",
  "Unpaid labeling",
  "Intellectual theft",
  "Copyright abuse",
  "Creative displacement",
  "Cultural appropriation",
  "Indigenous erasure",
  "Language extinction",
  "Digital divide",
  "Access inequality",
  "Tech elitism",
  "Education inequity",
  "Student debt",
  "Predatory lending",
  "Surveillance advertising",
  "Emotional manipulation",
  "Behavioral nudging",
  "Political microtargeting",
  "Fear monetization",
  "Trauma exploitation",
  "Crisis profiteering",
  "Disaster capitalism",
  "Pandemic profiteering",
  "War profiteering",
  "Security theater",
  "Risk externalization",
  "Liability avoidance",
  "Accountability gaps",
  "Ethics washing",
  "Performative activism"
];

router.get("/", async (_req, res) => {

  const rndTopic = starterTopics[Math.floor(Math.random() * starterTopics.length)]
  const goalFromTopic = await getGoalFromInitTopic(rndTopic);

  res.json({
    topic: rndTopic, 
    goal: goalFromTopic ?? "NONE"
  });

})

module.exports = router;